### ISSUE TITLE
Add an index to the documentation

### ISSUE THREAD

**Issue by ninkibah** [soasis/text#1]
Jean Heyd, sorry I couldn't figure out how to build your library from Clion.
But here's a patch file. I added genindex.rst which just has a title. I also added a configuration setting in conf.py.
This i scompletely untested, but something similar has worked on 3 of my internal libraries.

In my sphinx docs I don't use :ref:`genindex`, but I'm guessing this works too. Let me know if you need any further help.

[genindex.patch.zip](https://github.com/soasis/text/files/6016187/genindex.patch.zip)
Finally, one issue I had with my index was that my functions and classes were too long to fit in 2 columns. I was able to add some kind of template file to fix this. It's less necessary now that I can strip namespaces off.

**Comment by ThePhD** [comment]
Thanks for this! I didn't have to use the patch directly but I did get to place it in there. I do think I need to increase the width of the body: the fixed width right now is actually way too slim, and I should probably increase it by 15% or 20%...

**Comment by ninkibah** [comment]
To widen the page do the following:
In conf.py:
```python
html_css_files = [
    'custom.css',
]
```
And then add a custom.css in the _static directory:
```css
.wy-nav-content {
    max-width: 1200px !important;
}
```

You'll get more space for the 2 columns. It might also widen the other pages.
To go to a single column in the index, I needed to edit a file in the sphinx package. There may be a way to override this, but my python knowledge is read-only (barely).
