### ISSUE TITLE
Fails to build on OSX under GCC

### ISSUE THREAD

**Issue by nickelpro** [soasis/text#26]
See https://github.com/soasis/text/pull/25

**Comment by nickelpro** [comment]
Wait wtf
Tests fail: https://github.com/soasis/text/pull/25/commits/f48a7e3e28ed4d694e100cb82fc08a38c341c5a4
Tests pass: https://github.com/soasis/text/commit/938f9b380a1f0cc253959358f19cc77b34a91fcb

;lhdsgl;hdsahl;dalh;kADL'ADLK;AL;DH

**Comment by nickelpro** [comment]
The key to passing tests is running a high luck character. Luck increases success rate on all non-combat checks, such as Github test runners

**Comment by ThePhD** [comment]
It's fine, lol, the failures here aren't your fault.

**Comment by ThePhD** [comment]
But, this should now be fixed.

Thanks for all your help!
