### ISSUE TITLE
decode_view iterator post-increment operator is broken

### ISSUE THREAD

**Issue by nickelpro** [soasis/text#28]
It posts but it does not increment. 3/5 :star:'s, room for improvement

More things are also probably broken but I only wrote the test for the decode_view, see https://github.com/soasis/text/pull/27

**Comment by nickelpro** [comment]
Hmmm, seems to be intended?
```cpp
//////
/// @brief Increment a copy of the iterator.
///
/// @returns A copy to the incremented iterator.
//////
constexpr _Derived operator++(int) {
	_Derived __copy = this->_M_derived();
	++__copy;
	return __copy;
}
```

This is uh, not what I expect a post-increment operator to do

**Comment by ThePhD** [comment]
Yeah, I believe this should be `++(*this);`, and then return the copy.

**Comment by nickelpro** [comment]
I'll PR to fix it, just wanted to make sure this was an eclectic design choice

**Comment by nickelpro** [comment]
Fixed by https://github.com/soasis/text/pull/27

**Comment by ThePhD** [comment]
Thanks for taking care of this.
