### ISSUE TITLE
Encoding: punycode

### ISSUE THREAD

**Issue by ThePhD** [soasis/text#33]
Look into seeing if [Punycode](https://www.rfc-editor.org/rfc/rfc3492.txt) can be added to ztd.text.

**Comment by librarianmage** [comment]
since punycode kicks non-ascii characters to the end of the string, does it still fit into the decode/encode one interface?

**Comment by ThePhD** [comment]
Yes, but some changes need to be made to the design to accomodate it, with respect to state.

**Comment by ThePhD** [comment]
This was implemented in [cuneicode](https://github.com/soasis/cuneicode), and wrapped up to work here.
