### ISSUE TITLE
-fpermissive invalid conversion from ‘int’ to ‘std::ios_base::openmode’

### ISSUE THREAD

**Issue by rurban** [soasis/text#38]
g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

/usr/include/c++/11/fstream:534:7: note:   conversion of argument 2 would be ill-formed:
tests/additional_encodings/source/shift_jis.cpp:51:76: error: invalid conversion from ‘int’ to ‘std::ios_base::openmode’ [-fpermissive]
   51 |         std::ifstream expected_ifstr(expected_filename, std::ios_base::beg | std::ios_base::binary);
      |                                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
      |                                                                            |
      |                                                                            int

with clang++ 14.0.0

tests/additional_encodings/source/shift_jis.cpp:43:16: error: no matching constructor for initialization of 'std::ifstream' (aka 'basic_ifstream<char>')
        std::ifstream original_ifstr(original_filename, std::ios_base::beg | std::ios_base::binary);
                      ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/fstream:534:7: note: candidate constructor not viable: no known conversion from 'int' to 'ios_base::openmode' (aka 'std::_Ios_Openmode') for 2nd argument
      basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/fstream:567:7: note: candidate constructor not viable: no known conversion from 'int' to 'ios_base::openmode' (aka 'std::_Ios_Openmode') for 2nd argument
      basic_ifstream(const std::string& __s,
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/fstream:584:2: note: candidate template ignored: substitution failure [with _Path = const char *]: member reference base type 'const char *' is not a structure or union
        basic_ifstream(const _Path& __s,
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/fstream:590:7: note: candidate constructor not viable: requires 1 argument, but 2 were provided
      basic_ifstream(const basic_ifstream&) = delete;
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/fstream:592:7: note: candidate constructor not viable: requires single argument '__rhs', but 2 arguments were provided
      basic_ifstream(basic_ifstream&& __rhs)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/fstream:523:7: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
      basic_ifstream() : __istream_type(), _M_filebuf()
      ^

**Comment by ThePhD** [comment]
Yeah, this was my bad: it's been fixed! `std::ios_base::beg` was never supposed to be there.
