### ISSUE TITLE
__iterator aliases assume std::iterator_traits has members

### ISSUE THREAD

**Issue by cjdb** [soasis/text#8]
Most of the `__iterator_*` aliases depend on `std::iterator_traits`, but this doesn't necessarily mesh with C++20 iterators, since not all C++20 iterators necessarily have a populated `std::iterator_traits` (e.g. `stdr::iterator_t<stdr::basic_istream_view<char, char, std::char_traits<char>>>`).

Most of these either have a C++20 counterpart traits type (e.g. `value_type`) or can probably be worked out (e.g. `pointer`). One exception to this is `iterator_concept`, which might only exist as a member alias (e.g. `basic_istream_view`).

**Comment by ThePhD** [comment]
Wait. I thought `iterator_traits` was *required* to have all of its members populated, and that the iterator had to provide them, or else it would fail?

**Comment by ThePhD** [comment]
Oh. It's only for LegacyIterator types.

... Aaaaaamazing.....

**Comment by ThePhD** [comment]
This is fixed in the latest mega-commit simultaneous C++17 and C++20 support.

https://github.com/soasis/text/commit/963c137ff1c55ffc6404dd8f657b00b35c709091

Thanks for reporting!
